dist: trusty

language: python

node_js: "0.12"

python: "3.5"

cache:
  - directories: node_modules
  - pip

env:
  - PYTHONUNBUFFERED=TRUE

install:
  - npm install # Install task runners for lint checking.
  - pip install azure-mgmt-subscription azure-mgmt-resource keyring pycurl # Install Azure Python SDK (we only need the sub & the resource manager packages)

before_script:
  - ssh-keygen -q -f azure_moodle_id_rsa -N "" # Generate SSH keys to send to deployment

script:
  - npm test
  - ./etc/travis.py

